#!/bin/sh

. /lib/functions/uci-defaults.sh
. /lib/ralink.sh

set_usb_led() {
	ucidef_set_led_usbdev "usb" "USB" "$1" "1-1"
}

set_wifi_led() {
	ucidef_set_led_netdev "wifi_led" "wifi" "$1" "ra0"
}

set_wifi_led_5g() {
	ucidef_set_led_netdev "wifi_led_5g" "wifi_5g" "$1" "rai0"
}

case $(ralink_board_name) in
	fonera20n)
		set_usb_led "fonera20n:amber:usb"
		;;
	mtall| \
	ji2| \
	superdisk_mini| \
	vg100| \
	br100)
		set_wifi_led "wifi"
		;;
	wr8305rt)
		set_wifi_led "wr8305rt:wifi"
		set_usb_led "wr8305rt:usb"
		;;
	yk1)
		set_wifi_led "wifi:blue"
		set_usb_led "acc:blue"
		;;
	wrtnode)
		set_wifi_led "wrtnode:sys"
		;;
	abox)
		ucidef_set_led_usbdev "usb2" "USB2" "usb2:green" "1-2"
		ucidef_set_led_usbdev "usb3" "USB3" "usb3:green" "2-1"
		;;
	pbr-m1)
		set_wifi_led    "2g:blue"
		set_wifi_led_5g "5g:blue"
		;;
	creativebox)
		set_wifi_led    "2g"
		set_wifi_led_5g "5g"
		;;
	q7)
		set_wifi_led "zte_q7:wifi"
		;;
	dir620)
		set_wifi_led "d-link:green:wifi"
		set_usb_led "d-link:green:usb"
		;;
	ry1)
		set_wifi_led "ry1:wifi"
		set_usb_led "ry1:usb"
		;;
	xiaomi-mini)
		set_wifi_led "culiang:red"
		;;
	xiaomi-r1cl)
		set_wifi_led "status:blue"
		;;
	mt7620a-evb)
		set_wifi_led "wifi"
		set_usb_led "usb"
		;;
	ap7620a)
		set_wifi_led "wifi"
		set_usb_led "usb"
		;;
	nw718)
		set_usb_led "nw718:amber:usb"
		;;
	oye-0001)
		set_wifi_led "oye:green:wlan"
		;;
esac

ucidef_commit_leds

exit 0
