#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@upnpd[-1]
	add ucitrack upnpd
	set ucitrack.@upnpd[-1].init=miniupnpd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
/etc/init.d/miniupnpd enable
/etc/init.d/miniupnpd restart
exit 0
