#!/bin/sh
uci set luci.themes.LuciXEyE=/luci-static/LuciXEyE
[ "$(uci get luci.main.mediaurlbase)" == "/luci-static/material" ] || uci set luci.main.mediaurlbase="/luci-static/LuciXEyE"
uci commit luci
