#!/bin/sh

. /lib/ralink.sh

usb_status_led=""

led_set_attr() {
	[ -f "/sys/class/leds/$1/$2" ] && echo "$3" > "/sys/class/leds/$1/$2"
}

# status_led_set_timer() {
# 	led_set_attr $usb_status_led "trigger" "timer"
# 	led_set_attr $usb_status_led "delay_on" "$1"
# 	led_set_attr $usb_status_led "delay_off" "$2"
# }

usb_status_led_on() {
	led_set_attr $usb_status_led "trigger" "none"
	led_set_attr $usb_status_led "brightness" 255
}

usb_status_led_off() {
	led_set_attr $usb_status_led "trigger" "none"
	led_set_attr $usb_status_led "brightness" 0
}

device=`basename $DEVPATH`
case "$device" in
    sd*) ;;
    md*) ;;
    hd*);;      
    *) return;;
esac   
        
case $(ralink_board_name) in
  timecloud)
  usb_status_led="timecloud-led"
  ;;
  
  *) 
  return
  ;;
esac

case "$ACTION" in
    add)
		usb_status_led_on
		;;
    remove)
		usb_status_led_off
		;;
esac