#!/bin/sh /etc/rc.common

SERVICE_DAEMONIZE=1
START=90
STOP=15

start()
{
	config_load "chinadns"
	local enabled dns port
	config_get_bool enabled config enabled 0
	config_get dns config dns
	config_get port config port
	config_get_bool apnt_en config apnt_en 0

	[ $enabled = '0' ] && exit 0

	service_start /usr/bin/chinadns -c /etc/chinadns_chnroute.txt -p $port -s "$dns" $([ $apnt_en = '1' ] && echo "-m")
}

stop()
{
	service_stop /usr/bin/chinadns
}
