#!/bin/sh /etc/rc.common
# Copyright (C) 2015 PandoraBox Team

START=96

load_hwnat() {
	local enabled

	config_get_bool enabled $1 enabled 0

	if [ "$enabled" = "1" ]; then
		insmod hw_nat
		[ -f /dev/hwnat0 ] || mknod /dev/hwnat0 c 220 0
		hwnat -Z 2
		return
	else
	  rmmod hw_nat
	fi
}

load_hwcrypto() {
	local enabled

	config_get_bool enabled $1 enabled 0

	if [ "$enabled" = "1" ]; then
		insmod hw_crypto
		return
	fi
}


start() {
  	config_load hwacc
	[ -f /lib/modules/`uname -r`/hw_nat.ko ] && {
		config_foreach load_hwnat hwnat
	}
	[ -f /lib/modules/`uname -r`/hw_crypto.ko ] && {
		config_foreach load_hwcypto hwcypto
	}

}


stop() {
	[ -f /lib/modules/`uname -r`/hw_nat.ko ] && {
		rmmod hw_nat
	}
	
	[ -f /lib/modules/`uname -r`/hw_crypto.ko ] && {
		rmmod hw_crypto
	}

}
