#!/bin/sh /etc/rc.common
# Copyright (C) 2015 PandoraBox Team

START=96

HWNAT_OPTION=""

load_hwnat() {
	local enabled

	config_get_bool enabled $1 enabled 0
	config_get_bool tcp_offload $1 tcp_offload 0
	config_get_bool udp_offload $1 udp_offload 0
	config_get_bool ipv6_offload $1 ipv6_offload 0
	config_get_bool wifi_offload $1 wifi_offload 0
	
	[ "$tcp_offload" = "1" ] && HWNAT_OPTION="$HWNAT_OPTION tcp_offload=1"
	
	[ "$udp_offload" = "1" ] && HWNAT_OPTION="$HWNAT_OPTION udp_offload=1"
	
	[ "$ipv6_offload" = "1" ] && HWNAT_OPTION="$HWNAT_OPTION ipv6_offload=1"
	
	[ "$wifi_offload" = "1" ] && HWNAT_OPTION="$HWNAT_OPTION wifi_offload=1"
	
	if [ "$enabled" = "1" ]; then
		insmod hw_nat $HWNAT_OPTION
		[ ! -e /dev/hwnat0 ] && mknod /dev/hwnat0 c 220 0
		hwnat -Z 2
		return
	else
	  rmmod hw_nat
	fi
}

load_hwcrypto() {
	local enabled

	config_get_bool enabled $1 enabled 0

	if [ "$enabled" = "1" ]; then
		insmod hw_crypto
		return
	fi
}


start() {
	stop
	
  	config_load hwacc
	[ -f /lib/modules/`uname -r`/hw_nat.ko ] && {
		config_foreach load_hwnat hwnat
	}
	[ -f /lib/modules/`uname -r`/hw_crypto.ko ] && {
		config_foreach load_hwcypto hwcypto
	}

}


stop() {
	[ -f /lib/modules/`uname -r`/hw_nat.ko ] && {
		rmmod hw_nat
	}
	
	[ -f /lib/modules/`uname -r`/hw_crypto.ko ] && {
		rmmod hw_crypto
	}

}
