#!/bin/sh /etc/rc.common
#内网版花生壳 启动脚本
# Copyright (C) 2015 GuoGuo<gch981213@gmail.com>
START=99
STOP=10

start() {
	/usr/oray-app/bin/oraynewph -s 0.0.0.0 >/dev/null 2>/dev/null &
	/usr/oray-app/bin/oraysl -a 127.0.0.1 -p 16062 -s phsle01.oray.net:80 -d 2>&1 | logger -t oraysl
}

stop() {
	killall -9 oraynewph
	killall -9 oraysl
	rm /tmp/oraysl*
}
